using System;
using System.Collections.Generic;

namespace Euler
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
            EvenFibonacciNumbers();

        }

        static void EvenFibonacciNumbers()//https://projecteuler.net/problem=2
        {
            int current = 0;//current is the sum of the prevNums
            int sum = 2;//original sum.
            int[] prevNums = new int[2] { 1, 2 };
            while(1==1){
                current = prevNums[0] + prevNums[1];
                if (!(current < 4000000))
                    break;
                prevNums[0] = prevNums[1];
                prevNums[1] = current;
                if (current % 2 == 0)//if the number is even
                    sum += current;
            }//while
            Console.WriteLine($"The sum of the even-valued fibonacci terms that do not exceed four million is: {sum}");
        }
    }
}

//Each new term in the Fibonacci sequence is generated by adding the previous two terms.By starting with 1 and 2, the first 10 terms will be:

//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.